export const AUTH_ACTIONS = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOG_OUT: "LOG_OUT",
  REGISTER_REQUEST: "REGISTER_REQUEST",
};
export const MOVIES_ACTIONS = {
  FETCH_ALL_MOVIES: "FETCH_ALL_MOVIES",
  FETCH_CURRENT_MOVIE: "FETCH_CURRENT_MOVIE",
};
