export const AUTH_ACTIONS = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOG_OUT: "LOG_OUT",
  REGISTER_REQUEST: "REGISTER_REQUEST",
};
export const MOVIES_ACTIONS = {
  FETCH_CURRENT_PAGE: "FETCH_CURRENT_PAGE",
  FETCH_CURRENT_MOVIE: "FETCH_CURRENT_MOVIE",
  CHANGE_CURRENT_PAGE: "CHANGE_CURRENT_PAGE"
};
